### ISSUE TITLE
ht vendor prefix is taken. Use different vendor prefix

### ISSUE THREAD

**Issue by ojhaujjwal** [API-Skeletons/ht-user-registration-doctrine-orm#1]
Vendor prefix is used to resolve conflict between modules created by different people for example Zf-commons use `Zfc` as their prefix. The ht prefix is already taken by Hrevert Technologies. Please use a different prefix.

**Comment by TomHAnderson** [comment]
My experience shows the namespace gives distinction.

I don't think this is module is necessary truthfully and I'd like to work with hrevers/ht-user-registration-doctrine-orm to make a better module.  I see this module being consumed by hrevers and that would be a good thing.

In order to do that I need you, ojhaujjwal, to review both the comment on a new strategy.

**Comment by TomHAnderson** [comment]
I'll send in a PR for my enhancements to the original tomorrow and I look forward to your code-in-reverse.

**Comment by ojhaujjwal** [comment]
That is a very good idea. Thanks!
